# Escola de Engenharia - Eng. Civil
# TCC00239 - Programação de Computadores
# Turma I1 2024/1; Professor - John Reed
# Programador: Maurício Yan Barroso de Souza Mat: 124037033
# p0cabeca.py: Estrutura usual de um programa p/ aula
#
# Descrição dos objetos
# ...
# Boas vindas
# ...
# Diálogo de Entrada de Dados
# ...
# Processamento
# ...
# Emissão do relatório de saída
# ...
# Despedida
# ...
# Terminação
# ...